create table if not exists public.profiles (id uuid references auth.users on delete cascade primary key,email text not null,full_name text,avatar_url text,role text not null default 'pending' check (role in ('team','client','pending')),company text,created_at timestamptz default now());
alter table public.profiles enable row level security;
create policy "Team sees all" on profiles for select using (exists (select 1 from profiles where id=auth.uid() and role='team') or auth.uid()=id);
create policy "Users update own" on profiles for update using (auth.uid()=id);
create or replace function public.handle_new_user() returns trigger as $$ begin insert into public.profiles(id,email,full_name,role) values(new.id,new.email,new.raw_user_meta_data->>'full_name',coalesce(new.raw_user_meta_data->>'role','pending')); return new; end; $$ language plpgsql security definer;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table if not exists public.access_requests (id uuid default gen_random_uuid() primary key,email text not null,full_name text not null,company text,reason text,status text not null default 'pending' check (status in ('pending','approved','rejected')),created_at timestamptz default now());
alter table public.access_requests enable row level security;
create policy "Anyone can insert" on access_requests for insert with check (true);
create policy "Team can view" on access_requests for select using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create table if not exists public.contacts (id uuid default gen_random_uuid() primary key,name text not null,email text,company text,title text,phone text,notes text,tags text[],source text,created_by uuid references public.profiles(id),created_at timestamptz default now(),updated_at timestamptz default now());
alter table public.contacts enable row level security;
create policy "Team full access contacts" on contacts for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create table if not exists public.deals (id uuid default gen_random_uuid() primary key,title text not null,contact_id uuid references public.contacts(id),brand text not null,status text not null default 'new' check (status in ('new','in_talks','negotiating','active','complete','passed')),value numeric,currency text default 'USD',deliverables text,due_date date,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
alter table public.deals enable row level security;
create policy "Team full access deals" on deals for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create table if not exists public.notes (id uuid default gen_random_uuid() primary key,brand_id text not null,content text not null,author_id uuid references public.profiles(id),created_at timestamptz default now());
alter table public.notes enable row level security;
create policy "Team full access notes" on notes for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create table if not exists public.tasks (id uuid default gen_random_uuid() primary key,title text not null,description text,brand_id text,deal_id uuid references public.deals(id),assignee_id uuid references public.profiles(id),status text not null default 'todo' check (status in ('todo','in_progress','done')),priority text not null default 'medium' check (priority in ('low','medium','high')),due_date date,created_by uuid references public.profiles(id),created_at timestamptz default now(),updated_at timestamptz default now());
alter table public.tasks enable row level security;
create policy "Team full access tasks" on tasks for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create table if not exists public.content_ideas (id uuid default gen_random_uuid() primary key,title text not null,source_url text,source_type text default 'manual',brand_id text default 'the-good-meow',status text not null default 'idea' check (status in ('idea','writing','review','published')),assigned_to uuid references public.profiles(id),notes text,published_url text,created_at timestamptz default now());
alter table public.content_ideas enable row level security;
create policy "Team full access content" on content_ideas for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create table if not exists public.client_projects (id uuid default gen_random_uuid() primary key,name text not null,brand text not null,client_id uuid references public.profiles(id) on delete cascade,status text not null default 'in_progress' check (status in ('in_progress','review','complete','on_hold')),description text,updated_at timestamptz default now(),created_at timestamptz default now());
alter table public.client_projects enable row level security;
create policy "Team sees all projects" on client_projects for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create policy "Client sees own" on client_projects for select using (client_id=auth.uid());
create table if not exists public.client_messages (id uuid default gen_random_uuid() primary key,project_id uuid references public.client_projects(id) on delete cascade,content text not null,author_id uuid references public.profiles(id),is_team boolean not null default false,created_at timestamptz default now());
alter table public.client_messages enable row level security;
create policy "Team sees all messages" on client_messages for all using (exists (select 1 from profiles where id=auth.uid() and role='team'));
create policy "Client sees own messages" on client_messages for all using (exists (select 1 from client_projects where id=project_id and client_id=auth.uid()));
alter publication supabase_realtime add table notes;
alter publication supabase_realtime add table client_messages;
