import type { Agent } from './types'

export const AGENT_REGISTRY: Agent[] = [
  {
    id: 'nessie-chief-of-staff',
    name: 'Nessie',
    role: 'Chief of Staff (Lead Agent)',
    description: 'Chris\'s Donna. Leads the crew: assesses deals, plans the day, drafts in his voice, decides — Chris approves.',
    status: 'sandboxed',
    capabilities: ['plan', 'route', 'decompose', 'draft', 'summarize', 'suggest'],
    canExecuteExternalActions: false,
  },
  {
    id: 'hermes-coordinator',
    name: 'Hermes Coordinator',
    role: 'Dispatch & Routing',
    description: 'Works under Nessie: turns her plans into task packets and routes them across the crew.',
    status: 'sandboxed',
    capabilities: ['plan', 'route', 'decompose'],
    canExecuteExternalActions: false,
  },
  {
    id: 'brain-librarian',
    name: 'Brain Librarian',
    role: 'Memory & Knowledge',
    description: 'Indexes and summarizes notes from the second brain for quick recall.',
    status: 'sandboxed',
    capabilities: ['summarize', 'review-memory', 'suggest'],
    canExecuteExternalActions: false,
  },
  {
    id: 'safety-officer',
    name: 'Safety Officer',
    role: 'Safety & Review',
    description: 'Checks tasks against hard safety rules before anything moves forward.',
    status: 'sandboxed',
    capabilities: ['review-memory', 'suggest'],
    canExecuteExternalActions: false,
  },
  {
    id: 'outreach-drafter',
    name: 'Outreach Drafter',
    role: 'Drafting',
    description: 'Drafts outreach messages for partners, sponsors, and media — for review only.',
    status: 'sandboxed',
    capabilities: ['draft', 'suggest'],
    canExecuteExternalActions: false,
  },
  {
    id: 'care-case-organizer',
    name: 'Care Case Organizer',
    role: 'Case Management',
    description: 'Organizes pet care cases and surfaces what needs attention next.',
    status: 'sandboxed',
    capabilities: ['summarize', 'suggest', 'decompose'],
    canExecuteExternalActions: false,
  },
  {
    id: 'revenue-analyst',
    name: 'Revenue Analyst',
    role: 'Analysis',
    description: 'Summarizes revenue and fundraising signals from local data only.',
    status: 'sandboxed',
    capabilities: ['summarize', 'suggest'],
    canExecuteExternalActions: false,
  },
  {
    id: 'local-gateway-monitor',
    name: 'Local Gateway Monitor',
    role: 'Monitoring',
    description: 'Watches local gateway/OpenClaw status — read-only, no actions triggered.',
    status: 'sandboxed',
    capabilities: ['review-memory', 'suggest'],
    canExecuteExternalActions: false,
  },
  {
    id: 'cost-watcher',
    name: 'Cost Watcher',
    role: 'Token & Cost Monitoring',
    description: 'Tracks token and API cost estimates to keep routing cheap by default.',
    status: 'sandboxed',
    capabilities: ['summarize', 'suggest'],
    canExecuteExternalActions: false,
  },
]
